version: '3'
services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  books_service:
    build:
      context: ./books_service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
